import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";
import BtnWriteBoard from "./component/BtnWriteBoard";
import WriteBoard from "./component/WriteBoard";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "JJelly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  let writeBoard = 'dasdas';

  return (
    <html lang="en">
      <body className={inter.className }>
        <div id="wrap" className={writeBoard}>

            {/* 헤더 */}
            <Header />

            {children}

            {/* 푸터 */}
            {/* <Footer /> */}
        </div>

        <BtnWriteBoard writeBoard={writeBoard} />
        <WriteBoard writeBoard={writeBoard} />
      </body>
    </html>
  );
}
