import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "JJelly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="wrap">

            {/* 헤더 */}
            <Header />

            {children}

            {/* 푸터 */}
            <Footer />
        </div>

      </body>
    </html>
  );
}
