import { Inter, Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";


const noto = Noto_Sans_KR({
  subsets: ['latin'], // 또는 preload: false
});

export const metadata = {
  title: "JJelly",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={noto.className }>
        <div id="wrap">

            {/* 헤더 */}
            <Header />

            {children}

            {/* 푸터 */}
            <Footer />
        </div>
      </body>
    </html>
  );
}
